# This is a basic workflow to help you get started with Actions

name: Sweden

# Controls when the workflow will run
on:
  schedule:
    # should run every night at 2 am
    - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
          
      - name: Cloning DCAT-AP-Dumps-To-Feeds
        uses: actions/checkout@v4
        with:
          repository: pietercolpaert/DCAT-AP-Dumps-To-Feeds
          path: dumpstofeed

      - name: ⚙ Setting up ts-node
        run: |
          npm install -g typescript

      - name: 🏗 constructing the files for gh pages
        run: |
          cd dumpstofeed ; npm install ; cd ..
          bash dumpstofeed/workflow-sweden.sh
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "state-of-sweden sweden"
          author_name: Pieter Colpaert
          author_email: pieter.colpaert@ugent.be
          committer_name: Pieter’s bot
      - name: 🚀 Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
