# This is a basic workflow to help you get started with Actions

name: Sweden

# Controls when the workflow will run
on:
  schedule:
    # should run every night at 2 am
    - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          branch: gh-pages
          
      - uses: actions/checkout@v4
        with:
          name: pietercolpaert/DCAT-AP-Dumps-To-Feeds
          path: dumpstofeed

#      - name: ⚙ Setting up the nodejs env
#        run: |
#          echo I’ll probably need to set up more so I’m able to run ts-node?

      - name: 🏗 constructing the files for gh pages
        run: |
          cd dumptofeed ; npm install ; cd ..
          bash dumptofeed/workflow-sweden.sh
           
      - name: 🚀 Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
